export  const plans = [
  {
    id: "P-2D5563872K1616013MA4EJJQ",
    name: 'Start',
    description: 'Generate 10k* characters per month',
    disabled: false,
    features: [
      'Access 40+ use-cases',
      'Write in 30+ languages',
      'Access 20+ tones',
    ],
    monthly_price: 'Free',
    yearly_price: 0,
    duration: 'Start for free',
    buttonText: 'Upgrade',
  },
  {
    id: "P-51W76656242348941MA4FEXI",
    name: 'Saver Plan',
    description: 'Generate 100k* characters per month',
    disabled: false,
    features: [
      'Access 40+ use-cases',
      'Write in 30+ languages',
      'Access 20+ tones',
    ],
    monthly_price: '$9',
    yearly_price: '$99',
    duration: '/ mo',
    buttonText: 'Upgrade',
  },
  {
    id: "P-51W76656242348941MA4FEXC",
    name: 'Unlimited Plan',
    description: 'Generate UNLIMITED* characters per month',
    disabled: false,
    features: [
      'Access 40+ use-cases',
      'Write in 30+ languages',
      'Access 20+ tones',
      'Create your own custom use-case',
      'Dedicated account manager',
      'Priority email & chat support',
    ],
    monthly_price: '$29',
    yearly_price: '$129',
    duration: '/ mo',
    buttonText: 'Upgrade',
  },
];