name: CI
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run:  yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline

      - run: npx nx run andika-frontend:semantic-release && npx nx run andika-backend:semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}