name: Auto Release Version

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run:  yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline

      - run: npx nx run andika-frontend:semantic-release &&  npx nx run andika-backend:semantic-release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}