name: Auto Release Version

on:
  push:
    branches:
      - 'master'

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure Git User
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install npm dependencies
        run:  yarn install --frozen-lockfile --non-interactive --no-progress --prefer-offline


      - name: Release
        run: npx nx run andika-frontend:semantic-release &&  npx nx run andika-backend:semantic-release 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}